/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as Favicon48x48DotpngRouteImport } from './routes/favicon-48x48[.]png'
import { Route as Favicon32x32DotpngRouteImport } from './routes/favicon-32x32[.]png'
import { Route as Favicon16x16DotpngRouteImport } from './routes/favicon-16x16[.]png'
import { Route as AppleTouchIconDotpngRouteImport } from './routes/apple-touch-icon[.]png'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuadernoIndexRouteImport } from './routes/cuaderno.index'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal.aviso-legal'
import { Route as IrremediablesSlugRouteImport } from './routes/irremediables.$slug'
import { Route as CuadernoSlugRouteImport } from './routes/cuaderno.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const Favicon48x48DotpngRoute = Favicon48x48DotpngRouteImport.update({
  id: '/favicon-48x48.png',
  path: '/favicon-48x48.png',
  getParentRoute: () => rootRouteImport,
} as any)
const Favicon32x32DotpngRoute = Favicon32x32DotpngRouteImport.update({
  id: '/favicon-32x32.png',
  path: '/favicon-32x32.png',
  getParentRoute: () => rootRouteImport,
} as any)
const Favicon16x16DotpngRoute = Favicon16x16DotpngRouteImport.update({
  id: '/favicon-16x16.png',
  path: '/favicon-16x16.png',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleTouchIconDotpngRoute = AppleTouchIconDotpngRouteImport.update({
  id: '/apple-touch-icon.png',
  path: '/apple-touch-icon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadernoIndexRoute = CuadernoIndexRouteImport.update({
  id: '/cuaderno/',
  path: '/cuaderno/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IrremediablesSlugRoute = IrremediablesSlugRouteImport.update({
  id: '/irremediables/$slug',
  path: '/irremediables/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadernoSlugRoute = CuadernoSlugRouteImport.update({
  id: '/cuaderno/$slug',
  path: '/cuaderno/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/favicon-16x16.png': typeof Favicon16x16DotpngRoute
  '/favicon-32x32.png': typeof Favicon32x32DotpngRoute
  '/favicon-48x48.png': typeof Favicon48x48DotpngRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cuaderno/$slug': typeof CuadernoSlugRoute
  '/irremediables/$slug': typeof IrremediablesSlugRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/cuaderno/': typeof CuadernoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/favicon-16x16.png': typeof Favicon16x16DotpngRoute
  '/favicon-32x32.png': typeof Favicon32x32DotpngRoute
  '/favicon-48x48.png': typeof Favicon48x48DotpngRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cuaderno/$slug': typeof CuadernoSlugRoute
  '/irremediables/$slug': typeof IrremediablesSlugRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/cuaderno': typeof CuadernoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/favicon-16x16.png': typeof Favicon16x16DotpngRoute
  '/favicon-32x32.png': typeof Favicon32x32DotpngRoute
  '/favicon-48x48.png': typeof Favicon48x48DotpngRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cuaderno/$slug': typeof CuadernoSlugRoute
  '/irremediables/$slug': typeof IrremediablesSlugRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/cuaderno/': typeof CuadernoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apple-touch-icon.png'
    | '/favicon-16x16.png'
    | '/favicon-32x32.png'
    | '/favicon-48x48.png'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/sitemap.xml'
    | '/cuaderno/$slug'
    | '/irremediables/$slug'
    | '/legal/aviso-legal'
    | '/legal/privacidad'
    | '/cuaderno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apple-touch-icon.png'
    | '/favicon-16x16.png'
    | '/favicon-32x32.png'
    | '/favicon-48x48.png'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/sitemap.xml'
    | '/cuaderno/$slug'
    | '/irremediables/$slug'
    | '/legal/aviso-legal'
    | '/legal/privacidad'
    | '/cuaderno'
  id:
    | '__root__'
    | '/'
    | '/apple-touch-icon.png'
    | '/favicon-16x16.png'
    | '/favicon-32x32.png'
    | '/favicon-48x48.png'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/sitemap.xml'
    | '/cuaderno/$slug'
    | '/irremediables/$slug'
    | '/legal/aviso-legal'
    | '/legal/privacidad'
    | '/cuaderno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppleTouchIconDotpngRoute: typeof AppleTouchIconDotpngRoute
  Favicon16x16DotpngRoute: typeof Favicon16x16DotpngRoute
  Favicon32x32DotpngRoute: typeof Favicon32x32DotpngRoute
  Favicon48x48DotpngRoute: typeof Favicon48x48DotpngRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CuadernoSlugRoute: typeof CuadernoSlugRoute
  IrremediablesSlugRoute: typeof IrremediablesSlugRoute
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  CuadernoIndexRoute: typeof CuadernoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon-48x48.png': {
      id: '/favicon-48x48.png'
      path: '/favicon-48x48.png'
      fullPath: '/favicon-48x48.png'
      preLoaderRoute: typeof Favicon48x48DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon-32x32.png': {
      id: '/favicon-32x32.png'
      path: '/favicon-32x32.png'
      fullPath: '/favicon-32x32.png'
      preLoaderRoute: typeof Favicon32x32DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon-16x16.png': {
      id: '/favicon-16x16.png'
      path: '/favicon-16x16.png'
      fullPath: '/favicon-16x16.png'
      preLoaderRoute: typeof Favicon16x16DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple-touch-icon.png': {
      id: '/apple-touch-icon.png'
      path: '/apple-touch-icon.png'
      fullPath: '/apple-touch-icon.png'
      preLoaderRoute: typeof AppleTouchIconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuaderno/': {
      id: '/cuaderno/'
      path: '/cuaderno'
      fullPath: '/cuaderno/'
      preLoaderRoute: typeof CuadernoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irremediables/$slug': {
      id: '/irremediables/$slug'
      path: '/irremediables/$slug'
      fullPath: '/irremediables/$slug'
      preLoaderRoute: typeof IrremediablesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuaderno/$slug': {
      id: '/cuaderno/$slug'
      path: '/cuaderno/$slug'
      fullPath: '/cuaderno/$slug'
      preLoaderRoute: typeof CuadernoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppleTouchIconDotpngRoute: AppleTouchIconDotpngRoute,
  Favicon16x16DotpngRoute: Favicon16x16DotpngRoute,
  Favicon32x32DotpngRoute: Favicon32x32DotpngRoute,
  Favicon48x48DotpngRoute: Favicon48x48DotpngRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CuadernoSlugRoute: CuadernoSlugRoute,
  IrremediablesSlugRoute: IrremediablesSlugRoute,
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  CuadernoIndexRoute: CuadernoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
